<?php if ( is_active_sidebar( 'footer_kontakty_adresa' ) ) : ?>
	<div id="primary-sidebar" class="primary-sidebar widget-area" role="complementary">
		<?php dynamic_sidebar( 'footer_kontakty_adresa' ); ?>
	</div><!-- #primary-sidebar -->
<?php endif; ?>
<?php if ( is_active_sidebar( 'footer_kontakty_doba' ) ) : ?>
	<div id="primary-sidebar" class="primary-sidebar widget-area" role="complementary">
		<?php dynamic_sidebar( 'footer_kontakty_doba' ); ?>
	</div><!-- #primary-sidebar -->
<?php endif; ?>
<?php if ( is_active_sidebar( 'footer_kontakty' ) ) : ?>
	<div id="primary-sidebar" class="primary-sidebar widget-area" role="complementary">
		<?php dynamic_sidebar( 'footer_kontakty' ); ?>
	</div><!-- #primary-sidebar -->
<?php endif; ?>

